import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://wowclassicdb.com/wotlk/tooltip.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script strategy="beforeInteractive">
          {" "}
          {
            " const wowdbTooltipConfig = { colorLinks: true, renameLinks: true } "
          }
        </Script>
        <Script
          src="https://wowclassicdb.com/wotlk/tooltip.js"
          strategy="beforeInteractive"
        />
        <script
          type="text/javascript"
          src="http://cdn.cavernoftime.com/api/tooltip.js"
        ></script>

        <header className="sticky top-0 z-50 pb-6 bg-[#262626] lg:pb-0 drop-shadow-xl overflow-hidden">
          <div className="px-4 mx-auto w-screen sm:px-6 lg:px-8">
            <nav className="flex items-center justify-between h-16 lg:h-20">
              <a href="/" aria-label="Home">
                <img
                  className="w-auto h-20 lg:h-22 mt-4 cursor-pointer"
                  src="/sitelogo.png"
                  alt="Logo"
                />
              </a>
              <div className="flex gap-4">
                <button className="px-3 py-1.5 text-white rounded hover:bg-purple-700 transition">
                  Voting
                </button>
                <button className="px-3 py-1.5 text-white rounded hover:bg-purple-700 transition">
                  3D View
                </button>
                <button className="px-3 py-1.5 text-white  rounded hover:bg-purple-700 transition">
                  Forum
                </button>
              </div>
            </nav>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
